### ISSUE TITLE
Add version check to OOO plugin messages

### ISSUE THREAD

**Issue by WrinklyNinja** [boss-developers/oblivion#2]
OOO v1.35 dispenses with the Lite/Full split, instead there is a base plugin and several addon plugins. Some of the addon plugins are carried over from earlier versions of OOO, where they were addons to the Lite version, and so are producing "don't use" messages in BOSS.

Version checks should be added to correct this.

**Comment by deathssoul** [comment]
@mhahn123

Could you take a look at this one and see if it's still valid? I'd like to try and get this and #1 closed as part of general housekeeping if possible. :)
